### ISSUE TITLE
Implement Logging

### ISSUE THREAD

**Issue by karate** [karate/svn_curse#8]
Implement event logging (to file or stdout) with several logging levels (debug, info, warning etc)

May depend on #1

**Comment by geekyrajshri** [comment]
Hi I can try this

**Comment by Alig1493** [comment]
I this being done or has it been completed yet?

**Comment by karate** [comment]
I'm not sure. @geekyrajshri can you confirm you're working on it?

**Comment by geekyrajshri** [comment]
Hey,
I am on it will be completing it today and raise a PR

**Comment by karate** [comment]
Thank you. There's no hurry.

I  hope https://github.com/karate/svn_curse/pull/12 will be merged soon, so you may want to wait, or create a branch from this PR so we won't get any conflicts.

**Comment by karate** [comment]
Closed by #15
