### ISSUE TITLE
Read settings from file

### ISSUE THREAD

**Issue by karate** [karate/svn_curse#9]
Make the script read some basic settings from a file (eg: `config.txt`).

Variables that should be supported (add more at will):

- Colors
- svn username
- Keybindings (`j`/`k`, `w`, `r`)

**Comment by Alexius08** [comment]
I'm thinking of working on this. Currently, config.txt doesn't exist within the repository. If the script is intended to handle a nonexistent config.txt by making a file under said filename, what would be the initial variables and what would be their values?

**Comment by karate** [comment]
Thank you for your time.
If you implement this, you should add a `config.txt` file in the repo.
In case the file is not accessible (eg: the user deleted it, or he/she doesn't have read permissions), we have 2 options:

- Create a new config file with default settings (the ones the in repo config), or
- Assign default values on runtime.

You can implement whatever you chose,

In both cases, use the existing hard-coded values, except for the username, which won't have a default value.

**Comment by godfath3r** [comment]
Pythons ConfigParser builtin module could be a way to implement it.
